version: "1.0"
services:
  server:
    environment:
      - TEST_DB_HOST=psql
    container_name: app
    build:
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - psql
    links:
      - psql
    restart: always
  psql:
    image: postgres:14.4-alpine
    container_name: psql
    environment:
      - POSTGRES_USER=ui_test
      - POSTGRES_PASSWORD=ui_test
      # ${TEST_DB_NAME}
      # ${TEST_DB_USER}
      # ${TEST_DB_PASSWORD}
    ports:
      - 5432:5432
    restart: always